M452 REV A   PCB REV A   VARIABLE CLOCK
Updated: 1-Sep-2022

Test to observe clock pulses 880 BAUD and 220 BAUD
Also, a simple loop to measure the pulse output at pin R
Use an Oscilloscope to observe clock signals at pins H, J, M, N, L and K.
 880 Hz at H, J
 440 Hz at M, N
 220 Hz at K, L

PINS
 1 I AP2   P-INPUT

I
1
; initial state, just toggle high and low to observe the pulse on R
0
END
